/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.poly.booking.management.domain.kafka.model;
@org.apache.avro.specific.AvroGenerated
public enum NotificationStatus implements org.apache.avro.generic.GenericEnumSymbol<NotificationStatus> {
  SUCCESS, FAILED, PENDING, CANCELLED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"NotificationStatus\",\"namespace\":\"com.poly.booking.management.domain.kafka.model\",\"symbols\":[\"SUCCESS\",\"FAILED\",\"PENDING\",\"CANCELLED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
