/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.poly.booking.management.domain.kafka.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Room extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6608094226593357041L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Room\",\"namespace\":\"com.poly.booking.management.domain.kafka.model\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"roomNumber\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"basePrice\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"status\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Room> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Room> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Room> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Room> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Room> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Room to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Room from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Room instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Room fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String id;
  private java.lang.String roomNumber;
  private java.lang.String basePrice;
  private java.lang.String status;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Room() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param roomNumber The new value for roomNumber
   * @param basePrice The new value for basePrice
   * @param status The new value for status
   */
  public Room(java.lang.String id, java.lang.String roomNumber, java.lang.String basePrice, java.lang.String status) {
    this.id = id;
    this.roomNumber = roomNumber;
    this.basePrice = basePrice;
    this.status = status;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return roomNumber;
    case 2: return basePrice;
    case 3: return status;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = value$ != null ? value$.toString() : null; break;
    case 1: roomNumber = value$ != null ? value$.toString() : null; break;
    case 2: basePrice = value$ != null ? value$.toString() : null; break;
    case 3: status = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'roomNumber' field.
   * @return The value of the 'roomNumber' field.
   */
  public java.lang.String getRoomNumber() {
    return roomNumber;
  }


  /**
   * Sets the value of the 'roomNumber' field.
   * @param value the value to set.
   */
  public void setRoomNumber(java.lang.String value) {
    this.roomNumber = value;
  }

  /**
   * Gets the value of the 'basePrice' field.
   * @return The value of the 'basePrice' field.
   */
  public java.lang.String getBasePrice() {
    return basePrice;
  }


  /**
   * Sets the value of the 'basePrice' field.
   * @param value the value to set.
   */
  public void setBasePrice(java.lang.String value) {
    this.basePrice = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.String getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.String value) {
    this.status = value;
  }

  /**
   * Creates a new Room RecordBuilder.
   * @return A new Room RecordBuilder
   */
  public static com.poly.booking.management.domain.kafka.model.Room.Builder newBuilder() {
    return new com.poly.booking.management.domain.kafka.model.Room.Builder();
  }

  /**
   * Creates a new Room RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Room RecordBuilder
   */
  public static com.poly.booking.management.domain.kafka.model.Room.Builder newBuilder(com.poly.booking.management.domain.kafka.model.Room.Builder other) {
    if (other == null) {
      return new com.poly.booking.management.domain.kafka.model.Room.Builder();
    } else {
      return new com.poly.booking.management.domain.kafka.model.Room.Builder(other);
    }
  }

  /**
   * Creates a new Room RecordBuilder by copying an existing Room instance.
   * @param other The existing instance to copy.
   * @return A new Room RecordBuilder
   */
  public static com.poly.booking.management.domain.kafka.model.Room.Builder newBuilder(com.poly.booking.management.domain.kafka.model.Room other) {
    if (other == null) {
      return new com.poly.booking.management.domain.kafka.model.Room.Builder();
    } else {
      return new com.poly.booking.management.domain.kafka.model.Room.Builder(other);
    }
  }

  /**
   * RecordBuilder for Room instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Room>
    implements org.apache.avro.data.RecordBuilder<Room> {

    private java.lang.String id;
    private java.lang.String roomNumber;
    private java.lang.String basePrice;
    private java.lang.String status;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.poly.booking.management.domain.kafka.model.Room.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.roomNumber)) {
        this.roomNumber = data().deepCopy(fields()[1].schema(), other.roomNumber);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.basePrice)) {
        this.basePrice = data().deepCopy(fields()[2].schema(), other.basePrice);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.status)) {
        this.status = data().deepCopy(fields()[3].schema(), other.status);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing Room instance
     * @param other The existing instance to copy.
     */
    private Builder(com.poly.booking.management.domain.kafka.model.Room other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.roomNumber)) {
        this.roomNumber = data().deepCopy(fields()[1].schema(), other.roomNumber);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.basePrice)) {
        this.basePrice = data().deepCopy(fields()[2].schema(), other.basePrice);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.status)) {
        this.status = data().deepCopy(fields()[3].schema(), other.status);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.poly.booking.management.domain.kafka.model.Room.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.poly.booking.management.domain.kafka.model.Room.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'roomNumber' field.
      * @return The value.
      */
    public java.lang.String getRoomNumber() {
      return roomNumber;
    }


    /**
      * Sets the value of the 'roomNumber' field.
      * @param value The value of 'roomNumber'.
      * @return This builder.
      */
    public com.poly.booking.management.domain.kafka.model.Room.Builder setRoomNumber(java.lang.String value) {
      validate(fields()[1], value);
      this.roomNumber = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'roomNumber' field has been set.
      * @return True if the 'roomNumber' field has been set, false otherwise.
      */
    public boolean hasRoomNumber() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'roomNumber' field.
      * @return This builder.
      */
    public com.poly.booking.management.domain.kafka.model.Room.Builder clearRoomNumber() {
      roomNumber = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'basePrice' field.
      * @return The value.
      */
    public java.lang.String getBasePrice() {
      return basePrice;
    }


    /**
      * Sets the value of the 'basePrice' field.
      * @param value The value of 'basePrice'.
      * @return This builder.
      */
    public com.poly.booking.management.domain.kafka.model.Room.Builder setBasePrice(java.lang.String value) {
      validate(fields()[2], value);
      this.basePrice = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'basePrice' field has been set.
      * @return True if the 'basePrice' field has been set, false otherwise.
      */
    public boolean hasBasePrice() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'basePrice' field.
      * @return This builder.
      */
    public com.poly.booking.management.domain.kafka.model.Room.Builder clearBasePrice() {
      basePrice = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public java.lang.String getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.poly.booking.management.domain.kafka.model.Room.Builder setStatus(java.lang.String value) {
      validate(fields()[3], value);
      this.status = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public com.poly.booking.management.domain.kafka.model.Room.Builder clearStatus() {
      status = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Room build() {
      try {
        Room record = new Room();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.roomNumber = fieldSetFlags()[1] ? this.roomNumber : (java.lang.String) defaultValue(fields()[1]);
        record.basePrice = fieldSetFlags()[2] ? this.basePrice : (java.lang.String) defaultValue(fields()[2]);
        record.status = fieldSetFlags()[3] ? this.status : (java.lang.String) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Room>
    WRITER$ = (org.apache.avro.io.DatumWriter<Room>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Room>
    READER$ = (org.apache.avro.io.DatumReader<Room>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    if (this.roomNumber == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.roomNumber);
    }

    if (this.basePrice == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.basePrice);
    }

    if (this.status == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.status);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString();

      if (in.readIndex() != 1) {
        in.readNull();
        this.roomNumber = null;
      } else {
        this.roomNumber = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.basePrice = null;
      } else {
        this.basePrice = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.status = null;
      } else {
        this.status = in.readString();
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString();
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.roomNumber = null;
          } else {
            this.roomNumber = in.readString();
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.basePrice = null;
          } else {
            this.basePrice = in.readString();
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.status = null;
          } else {
            this.status = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










