version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: promotion-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: promotiondb
      POSTGRES_USER: promotion
      POSTGRES_PASSWORD: promotion
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: promotion-management:latest
    container_name: promotion-management-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/promotiondb
      SPRING_DATASOURCE_USERNAME: promotion
      SPRING_DATASOURCE_PASSWORD: promotion
      SPRING_LIQUIBASE_ENABLED: "true"
      MONITORING_SERVICE_URL: http://localhost:8081
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
