server:
  port: 8081

spring:
  application:
    name: inventory-service

openapi:
  service:
    api-docs: inventory-service-docs
    title: Inventory Service API
    version: 1.0.0
    server: http://localhost:8081
