server:
  port: 8088

spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DBMS_CONNECTION:jdbc:postgresql://localhost:5433/postgres?currentSchema=ai_management}
    username: ${DBMS_USERNAME:postgres}
    password: ${DBMS_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: ALWAYS
      schema-locations: classpath:init-schema.sql

  graphql:
    path: /graphql
    schema:
      locations: classpath:graphql/
    graphiql:
      enabled: true

  application:
    name: spring-management
  ai:
    ollama:
      base-url: ${OLLAMA_URL:http://localhost:11434}
      chat:
        model: ${MODEL:gemma:2b}
      embedding:
        model: nomic-embed-text
        enabled: true
  eureka:
    client:
      service-url:
        defaultZone: ${EUREKA:http://localhost:8761/}

  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:localhost}
      repositories:
        enabled: true

booking:
  room: ${BOOKING_URL:localhost://3000:/}