server:
  port: 8081

spring:
  application:
    name:
  datasource:
    url: jdbc:mysql://localhost:3306/
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

openapi:
  service:
    api-docs:
    title:
    version: 1.0.0
    server: http://localhost:8081
