server:
  port: 8092

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:postgresql://localhost:5433/postgres?currentSchema=authentication_service}
    username: ${DBMS_USERNAME:postgres}
    password: ${DBMS_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  sql:
    init:
      schema-locations: classpath:init-schema.sql
      data-locations: classpath:init-data.sql
      mode: always

  application:
    name: authentication-service

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/

  security:
    oauth2:
      client:
        registration:
          google:
            scope: email, profile
            redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:5173/login-success}
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET_KEY}

  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:localhost}