server:
  port: 8761

spring:
  application:
    name: eureka-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false # Tắt để dễ phát triển (ko tự giữ trạng thái)
    eviction-interval-timer-in-ms: 5000 # Tần suất quét service mất kết nối

