server:
  port: 8801

spring:
  application:
    name: inventory-service
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/inventory_management}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  sql:
    init:
      schema-locations: classpath:db_inventory.sql
      mode: always