server:
  port: 8801

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://localhost:3306/db_inventory
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  sql:
    init:
      schema-locations: classpath:db_inventory.sql

openapi:
  service:
    api-docs: inventory-service-docs
    title: Inventory Service API
    version: 1.0.0
    server: http://localhost:8801
