server:
  port: 8082
spring:
  application:
    name: restaurant-service
  datasource:
    url: jdbc:mysql://localhost:3306/db_restaurant
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

openapi:
  service:
    api-docs: restaurant-service-docs
    title: Restaurant Service API
    version: 1.0.0
    server: http://localhost:8082
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
