server:
  port: 8800

spring:
  application:
    name: swagger-hub
  cloud:
    discovery:
      enabled: true
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true
    instance:
      prefer-ip-address: true

# Cấu hình các service endpoints
services:
  swagger:
    inventory:
      name: Inventory Service
      url: http://localhost:8081
      docs-path: /v3/api-docs
      ui-path: /swagger-ui.html
    restaurant:
      name: Restaurant Service
      url: http://localhost:8082
      docs-path: /v3/api-docs
      ui-path: /swagger-ui.html
    booking:
      name: Booking Management
      url: http://localhost:8083
      docs-path: /v3/api-docs
      ui-path: /swagger-ui.html
    room:
      name: Room Management
      url: http://localhost:8087
      docs-path: /v3/api-docs
      ui-path: /swagger-ui.html
    spring-ai:
      name: Spring AI Management
      url: http://localhost:8088
      docs-path: /v3/api-docs
      ui-path: /swagger-ui.html
    staff:
      name: Staff Management
      url: http://localhost:8089
      docs-path: /staff-management/v3/api-docs
      ui-path: /staff-management/swagger-ui.html
    service-management:
      name: Service Management
      url: http://localhost:8090
      docs-path: /v3/api-docs
      ui-path: /swagger-ui.html
    notification:
      name: Notification Management
      url: http://localhost:8091
      docs-path: /v3/api-docs
      ui-path: /swagger-ui.html
    payment:
      name: Payment Management
      url: http://localhost:8092
      docs-path: /v3/api-docs
      ui-path: /swagger-ui.html
    customer:
      name: Customer Management
      url: http://localhost:8093
      docs-path: /v3/api-docs
      ui-path: /swagger-ui.html
    reporting:
      name: Reporting Management
      url: http://localhost:8094
      docs-path: /v3/api-docs
      ui-path: /swagger-ui.html

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /api-docs/swagger-config
    urls:
      - url: /api-docs/inventory
        name: Inventory Service
      - url: /api-docs/restaurant
        name: Restaurant Service
      - url: /api-docs/booking
        name: Booking Management
      - url: /api-docs/room
        name: Room Management
      - url: /api-docs/spring-ai
        name: Spring AI Management
      - url: /api-docs/staff
        name: Staff Management
      - url: /api-docs/service-management
        name: Service Management
      - url: /api-docs/notification
        name: Notification Management
      - url: /api-docs/payment
        name: Payment Management
      - url: /api-docs/customer
        name: Customer Management
      - url: /api-docs/reporting
        name: Reporting Management 