server:
  port: 8090 # Cổng của Gateway

spring:
  application:
    name: security-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: authentication_route
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/auth/**
            - Path=/users/**

        - id: booking_route
          uri: lb://BOOKING-MANAGEMENT
          predicates:
            - Path=/api/bookings/**

            # Thêm các route khác cho các microservice khác
            # - id: hotel_route
            #   uri: lb://HOTEL-MANAGEMENT
            #   predicates:
            #     - Path=/api/hotels/**

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/