# Cấu hình cho môi trường kiểm thử (test)
server.port=8501 # Cổng khác để tránh xung đột nếu chạy cùng lúc với dev

spring.application.name=notification-management-test
  
  # Cấu hình Mail (có thể mock hoặc dùng một dịch vụ mail test như GreenMail)
  # Trong các bài test hiện tại, EmailService đã được @MockBean, nên không cần cấu hình mail thực tế.
  # Nếu bạn muốn test gửi mail thực sự trong môi trường test, bạn sẽ cần cấu hình ở đây.
  # Ví dụ:
  # spring.mail.host=localhost
  # spring.mail.port=3025 # Cổng mặc định của GreenMail
  # spring.mail.username=testuser
  # spring.mail.password=testpass
  
  # Cấu hình Redis (cho OtpService)
  # Sử dụng Redis trong bộ nhớ hoặc một Redis instance riêng cho test
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password= # Nếu Redis của bạn có mật khẩu

# Cấu hình JPA/Hibernate cho test (nếu có DB)
# Sử dụng H2 trong bộ nhớ cho test để dữ liệu không bị lưu lại
# spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.hibernate.ddl-auto=create-drop # Tạo lại schema mỗi lần test
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
# spring.jpa.show-sql=true