package com.poly.customerdomain.model.entity.customer;

import com.poly.customerdomain.model.entity.Customer;
import com.poly.customerdomain.model.entity.valueobject.*;
import com.poly.customerdomain.model.exception.*;
import com.poly.domain.valueobject.CustomerId;
import com.poly.domain.valueobject.Money;
import org.junit.jupiter.api.Test;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

import static com.poly.customerdomain.model.entity.valueobject.Name.getFullName;
import static org.junit.jupiter.api.Assertions.*;

public class CustomerCreateTest {

    private final CustomerId customerId = new CustomerId(UUID.randomUUID());

//    @Test
//    void shouldCreateCustomerWithAutoGeneratedId() {
//        BehaviorData behavior = new BehaviorData("Deluxe", "BREAKFAST");
//
//        Customer customer = Customer.builder()
//                .customerId(customerId)
//                .userId(UUID.randomUUID())
//                .name(new Name("Nguyen", "Van A"))
//                .address(new Address("12 Lê Lợi", "Phường 4", "Quận 10", "TP.HCM"))
//                .dateOfBirth(new DateOfBirth(LocalDate.of(1980, 1, 1)))
//                .accumulatedSpending(new Money(BigDecimal.TEN))
//                .level(Level.GOLD)
//                .behaviorData(behavior)
//                .createdAt(LocalDateTime.now())
//                .updatedAt(LocalDateTime.now())
//                .build();
//        assertNotNull(customer.getId());
//        assertEquals("Nguyen Van A", Name.getFullName(customer.getFullName().getFirstName(),customer.getFullName().getLastName()));
//        System.out.println(customer.toString());
//    }

    @Test
    void shouldThrowExceptionWhenNameIsBlank() {
        // Act & Assert
        BlankCustomerNameException exception = assertThrows(
                BlankCustomerNameException.class,
                () -> new Name("", "") // code throw exception
        );
        // Optionally: Check context notice error
        assertEquals("Tên khách hàng không được để trống hoặc chỉ chứa khoảng trắng.", exception.getMessage());
    }

    @Test
    void shouldThrowExceptionWhenNameIsNull() {
        // Act & Assert
        BlankCustomerNameException exception = assertThrows(
                BlankCustomerNameException.class,
                () -> new Name(null, null) // code throw exception
        );
        // Optionally: Check context notice error
        assertEquals("Tên khách hàng không được để trống hoặc chỉ chứa khoảng trắng.", exception.getMessage());
    }

    @Test
    void shouldThrowExceptionWhenNameIsTooShort() {
        // Act & Assert
        CustomerNameLengthOutOfRangeException exception = assertThrows(
                CustomerNameLengthOutOfRangeException.class,
                () -> new Name("Nguy", "a")
        );
        // Optionally: Check context notice error
        assertEquals("Tên khách hàng phải có độ dài từ 5 đến 100 ký tự.", exception.getMessage());
    }

    @Test
    void shouldThrowExceptionWhenNameIsTooLong() {
        // Arrange
        String tooLongName = "a".repeat(101);
        // Act & Assert
        CustomerNameLengthOutOfRangeException exception = assertThrows(
                CustomerNameLengthOutOfRangeException.class,
                () -> new Name(tooLongName, "a")
        );
        // Optionally: Check context notice error
        assertEquals("Tên khách hàng phải có độ dài từ 5 đến 100 ký tự.", exception.getMessage());
    }

    @Test
    void shouldThrowExceptionWhenAddressIsTooShort() {
        // Act & Assert
        CustomerAddressLengthOutOfRangeException exception = assertThrows(
                CustomerAddressLengthOutOfRangeException.class,
                () -> new Address("", "test", "test", "test")
        );
        // Optionally: Check context notice error
        assertEquals("Địa chỉ khách hàng phải có độ dài từ 5 đến 100 ký tự.",  exception.getMessage());
    }

    @Test
    void shouldThrowExceptionWhenAddressIsTooLong() {
        // Arrange
        String addressToLong = "a".repeat(101);
        // Act & Assert
        CustomerAddressLengthOutOfRangeException exception = assertThrows(
                CustomerAddressLengthOutOfRangeException.class,
                () -> new Address(addressToLong, "test", "test", "test")
        );
        // Optionally: Check context notice error
        assertEquals("Địa chỉ khách hàng phải có độ dài từ 5 đến 100 ký tự.",  exception.getMessage());
    }

    @Test
    void shouldThrowExceptionWhenBirthTooLong() {
        // Act & Assert
        CustomerAgeOutOfRangeException exception = assertThrows(
                CustomerAgeOutOfRangeException.class,
                () -> new DateOfBirth(LocalDate.of(1080, 1, 1))
        );
        // Optionally: Check context notice error
        assertEquals("Tuổi phải nằm trong khoảng từ 15 đến 100.",  exception.getMessage());
    }

    @Test
    void shouldThrowExceptionWhenBirthTooShort() {
        // Act & Assert
        CustomerAgeOutOfRangeException exception = assertThrows(
                CustomerAgeOutOfRangeException.class,
                () -> new DateOfBirth(LocalDate.of(2020, 1, 1))
        );
        // Optionally: Check context notice error
        assertEquals("Tuổi phải nằm trong khoảng từ 15 đến 100.",  exception.getMessage());
    }

}
